version: 1
services:
  - type: web
    name: todo-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres
          property: connectionString
  - type: pserv
    name: todo-postgres
    plan: free
    databaseName: todolist
    user: todouser
